version: '3.8'

services:
  # Frontend Vue 3 (Servicio de desarrollo Vite)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: portfolio_frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-5173}:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_HOST=0.0.0.0
    networks:
      - portfolio_network
    stdin_open: true
    tty: true

networks:
  portfolio_network:
    driver: bridge
